function flagFromIso2(iso2) {
  const normalized = String(iso2 || "").toUpperCase();
  if (!/^[A-Z]{2}$/.test(normalized)) {
    return "🏳";
  }

  return String.fromCodePoint(
    normalized.charCodeAt(0) + 127397,
    normalized.charCodeAt(1) + 127397
  );
}

function country(code, iso2, name, dialCode) {
  return { code, iso2, name, dialCode, flag: flagFromIso2(iso2) };
}

export const COUNTRIES = [
  country("AF", "AF", "Afeganistao", "93"),
  country("ZA", "ZA", "Africa do Sul", "27"),
  country("AL", "AL", "Albania", "355"),
  country("DE", "DE", "Alemanha", "49"),
  country("AD", "AD", "Andorra", "376"),
  country("AO", "AO", "Angola", "244"),
  country("AG", "AG", "Antigua e Barbuda", "1-268"),
  country("SA", "SA", "Arabia Saudita", "966"),
  country("DZ", "DZ", "Argelia", "213"),
  country("AR", "AR", "Argentina", "54"),
  country("AM", "AM", "Armenia", "374"),
  country("AU", "AU", "Australia", "61"),
  country("AT", "AT", "Austria", "43"),
  country("AZ", "AZ", "Azerbaijao", "994"),
  country("BS", "BS", "Bahamas", "1-242"),
  country("BH", "BH", "Bahrein", "973"),
  country("BD", "BD", "Bangladesh", "880"),
  country("BB", "BB", "Barbados", "1-246"),
  country("BE", "BE", "Belgica", "32"),
  country("BZ", "BZ", "Belize", "501"),
  country("BJ", "BJ", "Benim", "229"),
  country("BM", "BM", "Bermudas", "1-441"),
  country("BY", "BY", "Bielorrussia", "375"),
  country("BO", "BO", "Bolivia", "591"),
  country("BA", "BA", "Bosnia e Herzegovina", "387"),
  country("BW", "BW", "Botsuana", "267"),
  country("BR", "BR", "Brasil", "55"),
  country("BN", "BN", "Brunei", "673"),
  country("BG", "BG", "Bulgaria", "359"),
  country("BF", "BF", "Burquina Faso", "226"),
  country("BI", "BI", "Burundi", "257"),
  country("BT", "BT", "Butao", "975"),
  country("CV", "CV", "Cabo Verde", "238"),
  country("CM", "CM", "Camaroes", "237"),
  country("KH", "KH", "Camboja", "855"),
  country("CA", "CA", "Canada", "1"),
  country("QA", "QA", "Catar", "974"),
  country("KZ", "KZ", "Cazaquistao", "7"),
  country("TD", "TD", "Chade", "235"),
  country("CL", "CL", "Chile", "56"),
  country("CN", "CN", "China", "86"),
  country("CY", "CY", "Chipre", "357"),
  country("CO", "CO", "Colombia", "57"),
  country("KM", "KM", "Comores", "269"),
  country("CG", "CG", "Congo-Brazzaville", "242"),
  country("CD", "CD", "Congo-Kinshasa", "243"),
  country("KP", "KP", "Coreia do Norte", "850"),
  country("KR", "KR", "Coreia do Sul", "82"),
  country("CI", "CI", "Costa do Marfim", "225"),
  country("CR", "CR", "Costa Rica", "506"),
  country("HR", "HR", "Croacia", "385"),
  country("CU", "CU", "Cuba", "53"),
  country("DK", "DK", "Dinamarca", "45"),
  country("DJ", "DJ", "Djibuti", "253"),
  country("DM", "DM", "Dominica", "1-767"),
  country("EG", "EG", "Egito", "20"),
  country("SV", "SV", "El Salvador", "503"),
  country("AE", "AE", "Emirados Arabes Unidos", "971"),
  country("EC", "EC", "Equador", "593"),
  country("ER", "ER", "Eritreia", "291"),
  country("SK", "SK", "Eslovaquia", "421"),
  country("SI", "SI", "Eslovenia", "386"),
  country("ES", "ES", "Espanha", "34"),
  country("US", "US", "Estados Unidos", "1"),
  country("EE", "EE", "Estonia", "372"),
  country("ET", "ET", "Etiopia", "251"),
  country("FJ", "FJ", "Fiji", "679"),
  country("PH", "PH", "Filipinas", "63"),
  country("FI", "FI", "Finlandia", "358"),
  country("FR", "FR", "Franca", "33"),
  country("GA", "GA", "Gabao", "241"),
  country("GM", "GM", "Gambia", "220"),
  country("GH", "GH", "Gana", "233"),
  country("GE", "GE", "Georgia", "995"),
  country("GI", "GI", "Gibraltar", "350"),
  country("GD", "GD", "Granada", "1-473"),
  country("GR", "GR", "Grecia", "30"),
  country("GL", "GL", "Groenlandia", "299"),
  country("GP", "GP", "Guadalupe", "590"),
  country("GU", "GU", "Guam", "1-671"),
  country("GT", "GT", "Guatemala", "502"),
  country("GY", "GY", "Guiana", "592"),
  country("GF", "GF", "Guiana Francesa", "594"),
  country("GN", "GN", "Guine", "224"),
  country("GQ", "GQ", "Guine Equatorial", "240"),
  country("GW", "GW", "Guine-Bissau", "245"),
  country("HT", "HT", "Haiti", "509"),
  country("HN", "HN", "Honduras", "504"),
  country("HK", "HK", "Hong Kong", "852"),
  country("HU", "HU", "Hungria", "36"),
  country("YE", "YE", "Iemen", "967"),
  country("KY", "KY", "Ilhas Cayman", "1-345"),
  country("CK", "CK", "Ilhas Cook", "682"),
  country("FO", "FO", "Ilhas Faroe", "298"),
  country("FK", "FK", "Ilhas Malvinas", "500"),
  country("MH", "MH", "Ilhas Marshall", "692"),
  country("SB", "SB", "Ilhas Salomao", "677"),
  country("IN", "IN", "India", "91"),
  country("ID", "ID", "Indonesia", "62"),
  country("IR", "IR", "Ira", "98"),
  country("IQ", "IQ", "Iraque", "964"),
  country("IE", "IE", "Irlanda", "353"),
  country("IS", "IS", "Islandia", "354"),
  country("IL", "IL", "Israel", "972"),
  country("IT", "IT", "Italia", "39"),
  country("JM", "JM", "Jamaica", "1-876"),
  country("JP", "JP", "Japao", "81"),
  country("JO", "JO", "Jordania", "962"),
  country("KI", "KI", "Kiribati", "686"),
  country("KW", "KW", "Kuwait", "965"),
  country("LA", "LA", "Laos", "856"),
  country("LS", "LS", "Lesoto", "266"),
  country("LV", "LV", "Letonia", "371"),
  country("LB", "LB", "Libano", "961"),
  country("LR", "LR", "Liberia", "231"),
  country("LY", "LY", "Libia", "218"),
  country("LI", "LI", "Liechtenstein", "423"),
  country("LT", "LT", "Lituania", "370"),
  country("LU", "LU", "Luxemburgo", "352"),
  country("MO", "MO", "Macau", "853"),
  country("MK", "MK", "Macedonia do Norte", "389"),
  country("MG", "MG", "Madagascar", "261"),
  country("MY", "MY", "Malasia", "60"),
  country("MW", "MW", "Malaui", "265"),
  country("MV", "MV", "Maldivas", "960"),
  country("ML", "ML", "Mali", "223"),
  country("MT", "MT", "Malta", "356"),
  country("MA", "MA", "Marrocos", "212"),
  country("MQ", "MQ", "Martinica", "596"),
  country("MU", "MU", "Mauricia", "230"),
  country("MR", "MR", "Mauritania", "222"),
  country("MX", "MX", "Mexico", "52"),
  country("MM", "MM", "Mianmar", "95"),
  country("FM", "FM", "Micronesia", "691"),
  country("MZ", "MZ", "Mocambique", "258"),
  country("MD", "MD", "Moldavia", "373"),
  country("MC", "MC", "Monaco", "377"),
  country("MN", "MN", "Mongolia", "976"),
  country("ME", "ME", "Montenegro", "382"),
  country("NA", "NA", "Namibia", "264"),
  country("NR", "NR", "Nauru", "674"),
  country("NP", "NP", "Nepal", "977"),
  country("NI", "NI", "Nicaragua", "505"),
  country("NE", "NE", "Niger", "227"),
  country("NG", "NG", "Nigeria", "234"),
  country("NU", "NU", "Niue", "683"),
  country("NO", "NO", "Noruega", "47"),
  country("NC", "NC", "Nova Caledonia", "687"),
  country("NZ", "NZ", "Nova Zelandia", "64"),
  country("OM", "OM", "Oma", "968"),
  country("NL", "NL", "Países Baixos", "31"),
  country("PW", "PW", "Palau", "680"),
  country("PA", "PA", "Panama", "507"),
  country("PG", "PG", "Papua-Nova Guine", "675"),
  country("PK", "PK", "Paquistao", "92"),
  country("PY", "PY", "Paraguai", "595"),
  country("PE", "PE", "Peru", "51"),
  country("PF", "PF", "Polinesia Francesa", "689"),
  country("PL", "PL", "Polonia", "48"),
  country("PR-787", "PR", "Porto Rico", "1-787"),
  country("PR-939", "PR", "Porto Rico", "1-939"),
  country("PT", "PT", "Portugal", "351"),
  country("KE", "KE", "Quenia", "254"),
  country("KG", "KG", "Quirguistao", "996"),
  country("GB", "GB", "Reino Unido", "44"),
  country("CF", "CF", "Republica Centro-Africana", "236"),
  country("CZ", "CZ", "Republica Checa", "420"),
  country("DO-809", "DO", "Republica Dominicana", "1-809"),
  country("DO-829", "DO", "Republica Dominicana", "1-829"),
  country("DO-849", "DO", "Republica Dominicana", "1-849"),
  country("RE", "RE", "Reuniao", "262"),
  country("RO", "RO", "Romenia", "40"),
  country("RW", "RW", "Ruanda", "250"),
  country("RU", "RU", "Russia", "7"),
  country("WS", "WS", "Samoa", "685"),
  country("AS", "AS", "Samoa Americana", "1-684"),
  country("LC", "LC", "Santa Lucia", "1-758"),
  country("KN", "KN", "Sao Cristovao e Nevis", "1-869"),
  country("SM", "SM", "Sao Marinho", "378"),
  country("ST", "ST", "Sao Tome e Principe", "239"),
  country("VC", "VC", "Sao Vicente e Granadinas", "1-784"),
  country("SN", "SN", "Senegal", "221"),
  country("SL", "SL", "Serra Leoa", "232"),
  country("RS", "RS", "Servia", "381"),
  country("SC", "SC", "Seychelles", "248"),
  country("SG", "SG", "Singapura", "65"),
  country("SY", "SY", "Siria", "963"),
  country("SO", "SO", "Somalia", "252"),
  country("LK", "LK", "Sri Lanka", "94"),
  country("SD", "SD", "Sudao", "249"),
  country("SS", "SS", "Sudao do Sul", "211"),
  country("SE", "SE", "Suecia", "46"),
  country("CH", "CH", "Suica", "41"),
  country("SR", "SR", "Suriname", "597"),
  country("TH", "TH", "Tailandia", "66"),
  country("TW", "TW", "Taiwan", "886"),
  country("TJ", "TJ", "Tajiquistao", "992"),
  country("TZ", "TZ", "Tanzania", "255"),
  country("TL", "TL", "Timor-Leste", "670"),
  country("TG", "TG", "Togo", "228"),
  country("TO", "TO", "Tonga", "676"),
  country("TT", "TT", "Trindade e Tobago", "1-868"),
  country("TN", "TN", "Tunisia", "216"),
  country("TM", "TM", "Turquemenistao", "993"),
  country("TR", "TR", "Turquia", "90"),
  country("TV", "TV", "Tuvalu", "688"),
  country("UA", "UA", "Ucrania", "380"),
  country("UG", "UG", "Uganda", "256"),
  country("UY", "UY", "Uruguai", "598"),
  country("UZ", "UZ", "Uzbequistao", "998"),
  country("VU", "VU", "Vanuatu", "678"),
  country("VA-3906", "VA", "Vaticano", "39-06"),
  country("VE", "VE", "Venezuela", "58"),
  country("VN", "VN", "Vietna", "84"),
  country("ZM", "ZM", "Zambia", "260"),
  country("ZW", "ZW", "Zimbabue", "263")
];

export const DEFAULT_COUNTRY_CODE = "US";

export function getCountryByCode(code) {
  return COUNTRIES.find((countryItem) => countryItem.code === code) ?? COUNTRIES[0];
}

export function getCountryByIso2(iso2) {
  const normalizedIso2 = String(iso2 || "").toUpperCase();
  return COUNTRIES.find((countryItem) => countryItem.iso2 === normalizedIso2) ?? null;
}
